### ISSUE TITLE
Is anything else required?

### ISSUE THREAD

**Issue by cbehan** [NickBeeuwsaert/loaf#1]
I followed the steps of "creating an app", adding the localhost URL and pasting the tokens into config.json. But when I run loaf, only a blank interface comes up.

One thing you didn't tell people to do is install the app to the workspace. When I tried this, the site told me that at least one feature has to be enabled. So I added the default incoming webhook. Are any other things needed for a successful login? Such as being an admin of your workspace?

The other clients I've used bypass this whole app section and use xoxp tokens instead. However, they are unfortunately not written in Python.

**Comment by NickBeeuwsaert** [comment]
I want to note that this is not really ready for use, it is/was more of a weekend project that I published.

But, I just tried to setup loaf from a clean venv from the instructions I put in the readme, and it worked for me. I am an admin in my workspace though, so that might be something to do with it.

You should be able to use the legacy token generation page to generate a xoxp token, and just put in in your `config.json`:

```
{
    "team": [
        {
            "name": "slack team alias",
            "token": "xoxp-..."
        }
    ]
}
```

 I don't think I knew about legacy tokens when I wrote loaf, so I went with the app route

**Comment by cbehan** [comment]
Thanks!
It looks like I have to add that webhook for each channel I want to use and the history doesn't go back very far. But that JSON file worked :).
